using ResolveAI.Api.Entities;
using ResolveAI.Api.Services;

namespace ResolveAI.Api.Tests;

public class AiIncidentServiceTests
{
    public void RunAllTests()
    {
        Console.WriteLine("\n--- AiIncidentServiceTests ---");

        Test_CanRunAIAnalysis_Permissions();
        Test_CanApplyAIRecommendation_Permissions();
        Test_Application_Uses_Stored_Recommendation_Not_Arbitrary_Client_Input();
        Test_AI_Exception_Mapping_Flags();
    }

    private void Test_CanRunAIAnalysis_Permissions()
    {
        var assignedTechId = Guid.NewGuid();
        var incident = new Incident { AssignedToId = assignedTechId };

        static bool CanRunAI(string? role, Guid userId, Incident inc)
        {
            return role switch
            {
                "Technician" => inc.AssignedToId == userId,
                "Manager" or "Admin" => true,
                _ => false
            };
        }

        // Employee cannot trigger AI
        Assert.False(CanRunAI("Employee", Guid.NewGuid(), incident), "Employee cannot trigger AI");

        // Assigned technician CAN trigger AI
        Assert.True(CanRunAI("Technician", assignedTechId, incident), "Assigned technician can trigger AI");

        // Unrelated technician CANNOT trigger AI
        Assert.False(CanRunAI("Technician", Guid.NewGuid(), incident), "Unrelated technician cannot trigger AI");

        // Manager and Admin CAN trigger AI
        Assert.True(CanRunAI("Manager", Guid.NewGuid(), incident), "Manager can trigger AI");
        Assert.True(CanRunAI("Admin", Guid.NewGuid(), incident), "Admin can trigger AI");

        Console.WriteLine("  ✓ CanRunAIAnalysis RBAC rules verified for all roles");
    }

    private void Test_CanApplyAIRecommendation_Permissions()
    {
        static bool CanApply(string? role) => role is "Manager" or "Admin";

        Assert.False(CanApply("Employee"), "Employee cannot apply AI recommendation");
        Assert.False(CanApply("Technician"), "Technician cannot apply AI recommendation");
        Assert.True(CanApply("Manager"), "Manager can apply AI recommendation");
        Assert.True(CanApply("Admin"), "Admin can apply AI recommendation");

        Console.WriteLine("  ✓ AI recommendation application restricted strictly to Manager and Admin");
    }

    private void Test_Application_Uses_Stored_Recommendation_Not_Arbitrary_Client_Input()
    {
        // Stored recommendation generated by AI service
        var storedAnalysis = new IncidentAIAnalysis
        {
            Id = Guid.NewGuid(),
            IncidentId = Guid.NewGuid(),
            CategoryRecommendation = "Hardware",
            PriorityRecommendation = "High",
            Confidence = 0.92,
            ReasoningSummary = "Power supply failure indicated by hardware diagnostic logs."
        };

        // Even if an attacker attempted to send arbitrary priority "Low",
        // the application flow uses storedAnalysis.CategoryRecommendation and storedAnalysis.PriorityRecommendation
        var targetCategory = storedAnalysis.CategoryRecommendation;
        var targetPriority = storedAnalysis.PriorityRecommendation;

        Assert.Equal("Hardware", targetCategory);
        Assert.Equal("High", targetPriority);

        // Verification that applied analysis records who approved it
        var approverId = Guid.NewGuid();
        storedAnalysis.AppliedByUserId = approverId;
        storedAnalysis.AppliedAt = DateTime.UtcNow;

        Assert.Equal(approverId, storedAnalysis.AppliedByUserId);
        Assert.NotNull(storedAnalysis.AppliedAt);

        Console.WriteLine("  ✓ AI recommendation application uses stored DB entity and records human approver");
    }

    private void Test_AI_Exception_Mapping_Flags()
    {
        var configEx = new AIIncidentAnalysisException("Missing API key", isConfigurationError: true);
        var timeoutEx = new AIIncidentAnalysisException("Request timed out", isConfigurationError: false);

        Assert.True(configEx.IsConfigurationError);
        Assert.False(timeoutEx.IsConfigurationError);

        var configMessage = configEx.IsConfigurationError
            ? "AI analysis is not configured."
            : "AI analysis is temporarily unavailable. Please try again.";

        var timeoutMessage = timeoutEx.IsConfigurationError
            ? "AI analysis is not configured."
            : "AI analysis is temporarily unavailable. Please try again.";

        Assert.Equal("AI analysis is not configured.", configMessage);
        Assert.Equal("AI analysis is temporarily unavailable. Please try again.", timeoutMessage);

        Console.WriteLine("  ✓ AI exception correctly differentiates configuration errors from transient downtime");
    }
}
