// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ResolveAI.Api.Data;

#nullable disable

namespace ResolveAI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915134102_AddIncidentAIAnalysis")]
    partial class AddIncidentAIAnalysis
    {
    }
}
